-- =============================================================================
-- KMFRI Scientists & Research Management System
-- DESTRUCTIVE RESET OF THE LEGACY PUBLIC SCHEMA (run ONCE, then re-run 0001)
-- =============================================================================
-- WHY THIS EXISTS
--   The target Supabase project already contained these table names with an
--   older, incompatible column layout. Because 0001_kmfri_schema.sql uses
--   CREATE TABLE IF NOT EXISTS, those pre-existing tables were skipped
--   silently and the migration then failed part-way through, for example:
--
--     ERROR: 42703: column "is_overdue" does not exist
--
--   raised by the index on line 418 of 0001_kmfri_schema.sql:
--     CREATE INDEX ... ON public.reports(status, due_date, is_overdue);
--
--   The table existed (legacy shape, no is_overdue) so the CREATE TABLE was
--   a no-op, and the index had nothing valid to reference.
--
-- WHAT YOU LOSE
--   Every row currently held in these tables. That is the legacy reference
--   data only (6 roles, 11 permissions, 4 directorates, 1 system_settings
--   row); all operational tables are already empty. Reference data is fully
--   regenerated by supabase/seed.sql, and role_permissions / audit history
--   are restored from data/kmfri_db.json by the Supabase mirror.
--
-- HOW TO USE
--   1. Run this script (Supabase dashboard -> SQL Editor -> New query).
--   2. Run supabase/migrations/0001_kmfri_schema.sql.
--   3. Run supabase/seed.sql.
--   4. Set SUPABASE_MIRROR_ENABLED=true in .env and restart the server.
--
--   Do NOT run this against a project holding data you need. If in doubt,
--   create a fresh Supabase project and run 0001 + seed there instead.
-- =============================================================================

BEGIN;

-- Child tables first (CASCADE covers the rest).
DROP TABLE IF EXISTS public.research_activities CASCADE;
DROP TABLE IF EXISTS public.output_authors CASCADE;
DROP TABLE IF EXISTS public.research_outputs CASCADE;
DROP TABLE IF EXISTS public.reports CASCADE;
DROP TABLE IF EXISTS public.documents CASCADE;
DROP TABLE IF EXISTS public.project_collaborators CASCADE;
DROP TABLE IF EXISTS public.collaborators CASCADE;
DROP TABLE IF EXISTS public.project_locations CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.funding CASCADE;
DROP TABLE IF EXISTS public.project_milestones CASCADE;
DROP TABLE IF EXISTS public.project_members CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.funders CASCADE;
DROP TABLE IF EXISTS public.shared_folders CASCADE;
DROP TABLE IF EXISTS public.chat_messages CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.email_dispatches CASCADE;
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.system_settings CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.research_areas CASCADE;
DROP TABLE IF EXISTS public.role_permissions CASCADE;
DROP TABLE IF EXISTS public.permissions CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.directorates CASCADE;

COMMIT;

-- Verification: this must return zero rows before you run 0001.
SELECT tablename
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN (
    'roles', 'permissions', 'role_permissions', 'directorates', 'research_areas',
    'users', 'funders', 'projects', 'project_members', 'project_milestones',
    'funding', 'locations', 'project_locations', 'collaborators',
    'project_collaborators', 'reports', 'research_outputs', 'output_authors',
    'documents', 'shared_folders', 'research_activities', 'notifications',
    'audit_logs', 'system_settings', 'chat_messages', 'email_dispatches'
  )
ORDER BY tablename;