import React, { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  Building2,
  Download,
  Mail,
  Phone,
  Plus,
  Search,
  X,
} from 'lucide-react';
import { useAuth } from '../context/AuthContext.tsx';
import {
  collaboratorFormSchema,
  PermissionCode,
} from '../types/kmfri.ts';
import { exportToCSV, exportToExcel, exportToInstitutionalReportHTML } from '../utils/exportUtils.ts';

type CollaboratorFormValues = z.infer<typeof collaboratorFormSchema>;

export function CollaboratorsModule() {
  const { db, user, apiFetch, refreshData, hasPermission, showToast } = useAuth();

  const [searchQuery, setSearchQuery] = useState('');
  const [typeFilter, setTypeFilter] = useState('all');
  const [modalOpen, setModalOpen] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const canManageCollaborators = hasPermission(PermissionCode.COLLABORATORS_MANAGE);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<CollaboratorFormValues>({
    resolver: zodResolver(collaboratorFormSchema),
    defaultValues: {
      organization_name: '',
      contact_person: '',
      email: '',
      phone: '+254 700 000000',
      country: 'Kenya',
      organization_type: 'University',
      collaboration_type: 'Joint Research',
      agreement_start_date: new Date().toISOString().split('T')[0],
      agreement_end_date: '2028-12-31',
      mou_status: 'Active',
      project_id: '',
      notes: '',
    },
  });

  const filteredCollaborators = useMemo(() => {
    if (!db) return [];
    return db.collaborators.filter((c) => {
      if (typeFilter !== 'all' && c.organization_type !== typeFilter) return false;
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const match =
          c.organization_name.toLowerCase().includes(q) ||
          c.contact_person.toLowerCase().includes(q) ||
          c.country.toLowerCase().includes(q);
        if (!match) return false;
      }
      return true;
    });
  }, [db, typeFilter, searchQuery]);

  if (!db) {
    return (
      <div className="min-h-[400px] flex items-center justify-center p-8">
        <div className="text-center space-y-3">
          <div className="w-8 h-8 rounded-full border-2 border-teal-500 border-t-transparent animate-spin mx-auto" />
          <div className="text-xs font-mono text-slate-500 dark:text-slate-400">
            Loading Strategic Collaborators & MOUs...
          </div>
        </div>
      </div>
    );
  }

  const onSubmitCollaborator = async (values: CollaboratorFormValues) => {
    setFormError(null);
    try {
      await apiFetch('/collaborators', {
        method: 'POST',
        body: JSON.stringify(values),
      });
      await refreshData();
      setModalOpen(false);
      reset();
      showToast(`Registered collaborator "${values.organization_name}"`);
    } catch (err: any) {
      setFormError(err.message);
    }
  };

  const handleExportCollaborators = (format: 'csv' | 'excel' | 'pdf') => {
    const rows = filteredCollaborators.map((c) => ({
      Organization: c.organization_name,
      Type: c.organization_type,
      Collaboration: c.collaboration_type,
      Country: c.country,
      Contact_Person: c.contact_person,
      Email: c.email,
      Phone: c.phone,
      MOU_Status: c.mou_status,
      Start_Date: c.agreement_start_date,
      End_Date: c.agreement_end_date,
    }));
    if (format === 'csv') exportToCSV('kmfri_collaborators', rows);
    if (format === 'excel') exportToExcel('kmfri_collaborators', 'Collaborators', rows);
    if (format === 'pdf') {
      exportToInstitutionalReportHTML(
        'kmfri_collaborators',
        'KMFRI Institutional Collaborators & MOU Registry',
        `Generated by ${user?.full_name}`,
        rows
      );
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5">
        <div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-white">
            Institutional Collaborators &amp; Partner Agreements
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Manage national and international research partners, universities, NGOs, and Memoranda of Understanding (MOUs)
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={() => handleExportCollaborators('csv')}
            className="px-2.5 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-medium hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center gap-1"
          >
            <Download className="w-3.5 h-3.5" />
            <span>CSV</span>
          </button>
          <button
            type="button"
            onClick={() => handleExportCollaborators('excel')}
            className="px-2.5 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-medium hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center gap-1"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Excel</span>
          </button>
          <button
            type="button"
            onClick={() => handleExportCollaborators('pdf')}
            className="px-2.5 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-medium hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center gap-1"
          >
            <Download className="w-3.5 h-3.5" />
            <span>PDF</span>
          </button>

          {canManageCollaborators && (
            <button
              type="button"
              onClick={() => {
                setFormError(null);
                setModalOpen(true);
              }}
              className="px-3.5 py-2 rounded-lg bg-[#0A2540] dark:bg-sky-600 text-white text-xs font-semibold flex items-center gap-1.5"
            >
              <Plus className="w-4 h-4" />
              <span>Register Collaborator</span>
            </button>
          )}
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-4 flex flex-col sm:flex-row gap-3 justify-between">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search partner organization, country, or contact..."
            className="w-full pl-9 pr-3 py-1.5 text-xs bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg"
          />
        </div>

        <select
          value={typeFilter}
          onChange={(e) => setTypeFilter(e.target.value)}
          className="px-3 py-1.5 text-xs bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg"
        >
          <option value="all">All Organization Types</option>
          <option value="University">University</option>
          <option value="Research Institute">Research Institute</option>
          <option value="Government Agency">Government Agency</option>
          <option value="NGO">NGO</option>
          <option value="International Body">International Body</option>
          <option value="Private Sector">Private Sector</option>
        </select>
      </div>

      {/* Collaborators Table */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden">
        {filteredCollaborators.length === 0 ? (
          <div className="py-14 px-6 text-center">
            <Building2 className="w-8 h-8 text-slate-400 mx-auto mb-2" />
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">
              No Partner Organizations Registered Yet
            </h3>
            <p className="text-xs text-slate-500 max-w-md mx-auto mt-1">
              Add universities, marine institutes, government ministries, or international conservation partners to track MOUs and joint projects.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-500">
                  <th className="py-3 px-4 font-semibold">Organization</th>
                  <th className="py-3 px-4 font-semibold">Type · Collaboration</th>
                  <th className="py-3 px-4 font-semibold">Contact Person</th>
                  <th className="py-3 px-4 font-semibold">Related Projects</th>
                  <th className="py-3 px-4 font-semibold">MOU Agreement Period</th>
                  <th className="py-3 px-4 font-semibold">MOU Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {filteredCollaborators.map((c) => {
                  const links = db.project_collaborators.filter(
                    (pc) => pc.collaborator_id === c.id
                  );
                  const relatedProjs = db.projects.filter((p) =>
                    links.some((l) => l.project_id === p.id)
                  );
                  return (
                    <tr key={c.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40">
                      <td className="py-3 px-4">
                        <div className="font-semibold text-slate-900 dark:text-white">
                          {c.organization_name}
                        </div>
                        <div className="text-[11px] text-slate-500">{c.country}</div>
                      </td>
                      <td className="py-3 px-4">
                        <div>{c.organization_type}</div>
                        <div className="text-[11px] text-sky-700 dark:text-sky-400">
                          {c.collaboration_type}
                        </div>
                      </td>
                      <td className="py-3 px-4">
                        <div className="font-medium">{c.contact_person}</div>
                        <div className="text-[11px] font-mono text-slate-500 flex items-center gap-2 mt-0.5">
                          <span className="flex items-center gap-1">
                            <Mail className="w-3 h-3" /> {c.email}
                          </span>
                          {c.phone && (
                            <span className="flex items-center gap-1">
                              <Phone className="w-3 h-3" /> {c.phone}
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="py-3 px-4 font-mono">
                        {relatedProjs.length === 0
                          ? 'Institutional'
                          : relatedProjs.map((p) => p.project_code).join(', ')}
                      </td>
                      <td className="py-3 px-4 font-mono text-[11px]">
                        {c.agreement_start_date} → {c.agreement_end_date}
                      </td>
                      <td className="py-3 px-4 font-mono font-semibold">{c.mou_status}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Add Collaborator Modal */}
      {modalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-950/60 flex items-center justify-center p-4">
          <div className="w-full max-w-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800 mb-4">
              <h3 className="text-base font-bold text-slate-900 dark:text-white">
                Register Partner Organization &amp; MOU
              </h3>
              <button type="button" onClick={() => setModalOpen(false)}>
                <X className="w-4 h-4 text-slate-400" />
              </button>
            </div>
            {formError && (
              <div className="mb-3 p-2.5 rounded bg-rose-50 text-xs text-rose-700">{formError}</div>
            )}
            <form onSubmit={handleSubmit(onSubmitCollaborator)} className="space-y-3 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-medium mb-1">Organization Name *</label>
                  <input
                    type="text"
                    {...register('organization_name')}
                    placeholder="Technical University of Mombasa (TUM)"
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                  {errors.organization_name && (
                    <p className="text-rose-600 mt-1">{errors.organization_name.message}</p>
                  )}
                </div>
                <div>
                  <label className="block font-medium mb-1">Country *</label>
                  <input
                    type="text"
                    {...register('country')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-medium mb-1">Organization Type *</label>
                  <select
                    {...register('organization_type')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  >
                    <option value="University">University</option>
                    <option value="Research Institute">Research Institute</option>
                    <option value="Government Agency">Government Agency</option>
                    <option value="NGO">NGO</option>
                    <option value="International Body">International Body</option>
                    <option value="Private Sector">Private Sector</option>
                  </select>
                </div>
                <div>
                  <label className="block font-medium mb-1">Collaboration Modality *</label>
                  <select
                    {...register('collaboration_type')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  >
                    <option value="Joint Research">Joint Research</option>
                    <option value="Funding Partner">Funding Partner</option>
                    <option value="Capacity Building">Capacity Building</option>
                    <option value="Data Exchange">Data Exchange</option>
                    <option value="Equipment Sharing">Equipment Sharing</option>
                    <option value="Policy Advisory">Policy Advisory</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block font-medium mb-1">Contact Person *</label>
                  <input
                    type="text"
                    {...register('contact_person')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">Contact Email *</label>
                  <input
                    type="email"
                    {...register('email')}
                    className="w-full px-3 py-2 font-mono rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">Phone *</label>
                  <input
                    type="text"
                    {...register('phone')}
                    className="w-full px-3 py-2 font-mono rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block font-medium mb-1">Agreement Start *</label>
                  <input
                    type="date"
                    {...register('agreement_start_date')}
                    className="w-full px-3 py-2 font-mono rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">Agreement End *</label>
                  <input
                    type="date"
                    {...register('agreement_end_date')}
                    className="w-full px-3 py-2 font-mono rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">MOU Status *</label>
                  <select
                    {...register('mou_status')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  >
                    <option value="Active">Active</option>
                    <option value="Draft">Draft</option>
                    <option value="Renewal Pending">Renewal Pending</option>
                    <option value="Expired">Expired</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block font-medium mb-1">Link to Project (Optional)</label>
                <select
                  {...register('project_id')}
                  className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                >
                  <option value="">Institutional Agreement (All Projects)</option>
                  {db.projects.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.project_code} — {p.title}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setModalOpen(false)}
                  className="px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-700"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-4 py-2 rounded-lg bg-[#0A2540] dark:bg-sky-600 text-white font-semibold"
                >
                  Save Collaborator
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
