import React, { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  Download,
  MapPin,
  Plus,
  Search,
  X,
} from 'lucide-react';
import { useAuth } from '../context/AuthContext.tsx';
import {
  locationFormSchema,
  PermissionCode,
} from '../types/kmfri.ts';
import { GisMapCanvas } from './GisMapCanvas.tsx';
import { exportToCSV, exportToExcel, exportToInstitutionalReportHTML } from '../utils/exportUtils.ts';

type LocationFormValues = z.infer<typeof locationFormSchema>;

export function LocationsModule() {
  const { db, user, apiFetch, refreshData, hasPermission, showToast } = useAuth();

  const [searchQuery, setSearchQuery] = useState('');
  const [countyFilter, setCountyFilter] = useState('all');
  const [areaTypeFilter, setAreaTypeFilter] = useState('all');
  const [modalOpen, setModalOpen] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [clickedCoords, setClickedCoords] = useState<{ lat: number; lng: number } | null>(null);

  const canManageLocations = hasPermission(PermissionCode.LOCATIONS_MANAGE);

  const {
    register,
    handleSubmit,
    setValue,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<LocationFormValues>({
    resolver: zodResolver(locationFormSchema) as any,
    defaultValues: {
      country: 'Kenya',
      county: 'Mombasa',
      sub_county: 'Nyali',
      site_name: '',
      latitude: -4.0435,
      longitude: 39.6682,
      marine_coastal_area: 'Inshore Reef',
      description: '',
      project_id: '',
      activity_summary: '',
    },
  });

  const counties = useMemo(() => {
    const s = new Set<string>(['Mombasa', 'Kilifi', 'Kwale', 'Lamu', 'Tana River', 'Kisumu', 'Kirinyaga']);
    if (db) {
      db.locations.forEach((l) => s.add(l.county));
    }
    return Array.from(s);
  }, [db?.locations]);

  const filteredLocations = useMemo(() => {
    if (!db) return [];
    return db.locations.filter((l) => {
      if (countyFilter !== 'all' && l.county !== countyFilter) return false;
      if (areaTypeFilter !== 'all' && l.marine_coastal_area !== areaTypeFilter) return false;
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const match =
          l.site_name.toLowerCase().includes(q) ||
          l.county.toLowerCase().includes(q) ||
          l.sub_county.toLowerCase().includes(q) ||
          l.description.toLowerCase().includes(q);
        if (!match) return false;
      }
      return true;
    });
  }, [db, countyFilter, areaTypeFilter, searchQuery]);

  if (!db) {
    return (
      <div className="min-h-[400px] flex items-center justify-center p-8">
        <div className="text-center space-y-3">
          <div className="w-8 h-8 rounded-full border-2 border-teal-500 border-t-transparent animate-spin mx-auto" />
          <div className="text-xs font-mono text-slate-500 dark:text-slate-400">
            Loading Geospatial Intelligence & Field Sites...
          </div>
        </div>
      </div>
    );
  }

  const handleMapClickCoordinates = (lat: number, lng: number) => {
    setClickedCoords({ lat, lng });
    setValue('latitude', lat);
    setValue('longitude', lng);
    if (canManageLocations && !modalOpen) {
      setModalOpen(true);
    }
  };

  const onSubmitLocation = async (values: LocationFormValues) => {
    setFormError(null);
    try {
      await apiFetch('/locations', {
        method: 'POST',
        body: JSON.stringify(values),
      });
      await refreshData();
      setModalOpen(false);
      setClickedCoords(null);
      reset();
      showToast(`Registered GIS station "${values.site_name}"`);
    } catch (err: any) {
      setFormError(err.message);
    }
  };

  const handleExportLocations = (format: 'csv' | 'excel' | 'pdf') => {
    const rows = filteredLocations.map((l) => {
      const link = db.project_locations.find((pl) => pl.location_id === l.id);
      const proj = link ? db.projects.find((p) => p.id === link.project_id) : null;
      return {
        Site_Name: l.site_name,
        Country: l.country,
        County: l.county,
        Sub_County: l.sub_county,
        Marine_Coastal_Area: l.marine_coastal_area,
        Latitude: l.latitude,
        Longitude: l.longitude,
        Linked_Project: proj?.project_code || '—',
        Activity: link?.activity_summary || '—',
      };
    });
    if (format === 'csv') exportToCSV('kmfri_gis_locations', rows);
    if (format === 'excel') exportToExcel('kmfri_gis_locations', 'Locations', rows);
    if (format === 'pdf') {
      exportToInstitutionalReportHTML(
        'kmfri_gis_locations',
        'KMFRI GIS Marine, Coastal & Inland Sampling Stations',
        `Generated by ${user?.full_name}`,
        rows
      );
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5">
        <div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-white">
            GIS Project Locations &amp; Marine Sampling Stations
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Interactive spatial registry across Kenyan EEZ offshore waters, coral reefs, mangrove creeks, and freshwater lakes
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={() => handleExportLocations('csv')}
            className="px-2.5 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-medium hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center gap-1"
          >
            <Download className="w-3.5 h-3.5" />
            <span>CSV</span>
          </button>
          <button
            type="button"
            onClick={() => handleExportLocations('excel')}
            className="px-2.5 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-medium hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center gap-1"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Excel</span>
          </button>
          <button
            type="button"
            onClick={() => handleExportLocations('pdf')}
            className="px-2.5 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-medium hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center gap-1"
          >
            <Download className="w-3.5 h-3.5" />
            <span>PDF</span>
          </button>

          {canManageLocations && (
            <button
              type="button"
              onClick={() => {
                setFormError(null);
                setModalOpen(true);
              }}
              className="px-3.5 py-2 rounded-lg bg-[#0A2540] dark:bg-sky-600 text-white text-xs font-semibold flex items-center gap-1.5"
            >
              <Plus className="w-4 h-4" />
              <span>Register GIS Station</span>
            </button>
          )}
        </div>
      </div>

      {/* Interactive GIS Map */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 space-y-4">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="relative">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search site name, county, or sub-county..."
              className="w-full pl-9 pr-3 py-2 text-xs bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg"
            />
          </div>

          <select
            value={countyFilter}
            onChange={(e) => setCountyFilter(e.target.value)}
            className="px-3 py-2 text-xs bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg"
          >
            <option value="all">All Counties</option>
            {counties.map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>

          <select
            value={areaTypeFilter}
            onChange={(e) => setAreaTypeFilter(e.target.value)}
            className="px-3 py-2 text-xs bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg"
          >
            <option value="all">All Marine &amp; Coastal Ecosystem Types</option>
            <option value="Inshore Reef">Inshore Reef</option>
            <option value="Mangrove Creek">Mangrove Creek</option>
            <option value="EEZ Offshore">EEZ Offshore</option>
            <option value="Estuary">Estuary</option>
            <option value="Seagrass Meadow">Seagrass Meadow</option>
            <option value="Freshwater Lake">Freshwater Lake</option>
            <option value="Riverine Basin">Riverine Basin</option>
            <option value="Aquaculture Station">Aquaculture Station</option>
          </select>
        </div>

        {/* GIS Map Live Telemetry Status Bar */}
        <div className="flex flex-wrap items-center justify-between gap-2 px-3 py-2 bg-slate-50 dark:bg-slate-950/80 border border-slate-200 dark:border-slate-800 rounded-lg text-xs">
          <div className="flex items-center gap-2 text-slate-700 dark:text-slate-300">
            <span className="inline-flex items-center gap-1 font-semibold text-sky-700 dark:text-sky-400">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              Sovereign GIS Basemap Live
            </span>
            <span className="text-slate-400">·</span>
            <span className="text-slate-500 dark:text-slate-400">
              13 KMFRI Stations &middot; 200NM Kenyan EEZ Vector &middot; Bathymetric Isobaths (-200m / -1000m)
            </span>
          </div>
          <div className="text-[11px] font-mono text-slate-500 dark:text-slate-400">
            {canManageLocations ? '🎯 Click anywhere on the map to pin new station coordinates' : '🗺️ Telemetry Active'}
          </div>
        </div>

        <GisMapCanvas
          locations={filteredLocations}
          heightClass="h-[680px] sm:h-[750px] lg:h-[820px]"
          onMapClickCoordinates={canManageLocations ? handleMapClickCoordinates : undefined}
          selectedCoordinates={clickedCoords}
        />
      </div>

      {/* Locations Table */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden">
        {filteredLocations.length === 0 ? (
          <div className="py-12 px-6 text-center">
            <MapPin className="w-8 h-8 text-slate-400 mx-auto mb-2" />
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">
              No GIS Sampling Stations Registered Yet
            </h3>
            <p className="text-xs text-slate-500 max-w-md mx-auto mt-1">
              Click anywhere on the interactive map above or click "Register GIS Station" to add coordinates for coral reefs, mangrove creeks, offshore stations, or inland lakes.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-500">
                  <th className="py-3 px-4 font-semibold">Station / Site Name</th>
                  <th className="py-3 px-4 font-semibold">County · Sub-County</th>
                  <th className="py-3 px-4 font-semibold">Ecosystem / Area</th>
                  <th className="py-3 px-4 font-semibold">Coordinates (Lat, Lng)</th>
                  <th className="py-3 px-4 font-semibold">Linked Project &amp; Activity</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {filteredLocations.map((loc) => {
                  const link = db.project_locations.find((pl) => pl.location_id === loc.id);
                  const proj = link ? db.projects.find((p) => p.id === link.project_id) : null;
                  return (
                    <tr key={loc.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40">
                      <td className="py-3 px-4">
                        <div className="font-semibold text-slate-900 dark:text-white">
                          {loc.site_name}
                        </div>
                        <div className="text-[11px] text-slate-500">{loc.description || '—'}</div>
                      </td>
                      <td className="py-3 px-4">
                        {loc.county} · {loc.sub_county} ({loc.country})
                      </td>
                      <td className="py-3 px-4 font-mono text-sky-700 dark:text-sky-400">
                        {loc.marine_coastal_area}
                      </td>
                      <td className="py-3 px-4 font-mono tabular-nums">
                        {loc.latitude.toFixed(5)}°, {loc.longitude.toFixed(5)}°
                      </td>
                      <td className="py-3 px-4">
                        {proj ? (
                          <div>
                            <span className="font-mono font-semibold">{proj.project_code}</span>
                            <span className="text-slate-400 mx-1">·</span>
                            <span className="text-slate-500">{link?.activity_summary}</span>
                          </div>
                        ) : (
                          <span className="text-slate-400">Unlinked</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Register Location Modal */}
      {modalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-950/60 flex items-center justify-center p-4">
          <div className="w-full max-w-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800 mb-4">
              <h3 className="text-base font-bold text-slate-900 dark:text-white">
                Register GIS Sampling Station / Site
              </h3>
              <button type="button" onClick={() => setModalOpen(false)}>
                <X className="w-4 h-4 text-slate-400" />
              </button>
            </div>
            {formError && (
              <div className="mb-3 p-2.5 rounded bg-rose-50 text-xs text-rose-700">{formError}</div>
            )}
            <form onSubmit={handleSubmit(onSubmitLocation)} className="space-y-3 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-medium mb-1">Site / Station Name *</label>
                  <input
                    type="text"
                    {...register('site_name')}
                    placeholder="Gazi Bay Mangrove Carbon Flux Tower"
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                  {errors.site_name && (
                    <p className="text-rose-600 mt-1">{errors.site_name.message}</p>
                  )}
                </div>
                <div>
                  <label className="block font-medium mb-1">Marine / Coastal Area *</label>
                  <select
                    {...register('marine_coastal_area')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  >
                    <option value="Inshore Reef">Inshore Reef</option>
                    <option value="Mangrove Creek">Mangrove Creek</option>
                    <option value="EEZ Offshore">EEZ Offshore</option>
                    <option value="Estuary">Estuary</option>
                    <option value="Seagrass Meadow">Seagrass Meadow</option>
                    <option value="Freshwater Lake">Freshwater Lake</option>
                    <option value="Riverine Basin">Riverine Basin</option>
                    <option value="Aquaculture Station">Aquaculture Station</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block font-medium mb-1">Country *</label>
                  <input
                    type="text"
                    {...register('country')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">County *</label>
                  <input
                    type="text"
                    {...register('county')}
                    placeholder="Kwale"
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">Sub-County *</label>
                  <input
                    type="text"
                    {...register('sub_county')}
                    placeholder="Msambweni"
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-medium mb-1">Latitude (-90 to 90) *</label>
                  <input
                    type="number"
                    step="any"
                    {...register('latitude')}
                    className="w-full px-3 py-2 font-mono rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">Longitude (-180 to 180) *</label>
                  <input
                    type="number"
                    step="any"
                    {...register('longitude')}
                    className="w-full px-3 py-2 font-mono rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-medium mb-1">Link to Project (Optional)</label>
                  <select
                    {...register('project_id')}
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  >
                    <option value="">None / Institutional Station</option>
                    {db.projects.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.project_code} — {p.title}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block font-medium mb-1">Activity at Site</label>
                  <input
                    type="text"
                    {...register('activity_summary')}
                    placeholder="Benthic transect & CTD cast"
                    className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                  />
                </div>
              </div>

              <div>
                <label className="block font-medium mb-1">Ecological / Site Description</label>
                <textarea
                  rows={2}
                  {...register('description')}
                  className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950"
                />
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setModalOpen(false)}
                  className="px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-700"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-4 py-2 rounded-lg bg-[#0A2540] dark:bg-sky-600 text-white font-semibold"
                >
                  Save GIS Station
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
